
GET http://localhost:3000/users

###

GET http://localhost:3000/users/61eef004e40c8d9a8acefeed

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email":"joazinho@gmail.com",
    "senha": "senhalegal"
}

###


